### ISSUE TITLE
Integrate MathWebSearch into MathHub

### ISSUE THREAD

**Issue by tkw1536** [MathHubInfo/MathHub#3]
We want to integrate MathWebSearch into MathHub and allow searches directly from the MathHub interface. 

- [x] Run a simple MathWebSearch Instance
- [ ] Run a TemaSearch Instance
- [ ] Update the Frontend
- [ ] Build a generic OMDOC harvester
- [ ] Package, Deploy and Scale
