### ISSUE TITLE
Distribute generated files (OMDoc, ...) 

### ISSUE THREAD

**Issue by tkw1536** [MathHubInfo/MathHub#5]
- [ ] implement generated content branches inside mmt/lmh
- [ ] automatically pull and re-load regularly or when an archive  changes. 
- [ ] document this in the [wiki page](https://github.com/MathHubInfo/Documentation/wiki/build-system)
