### ISSUE TITLE
fully support private MathHubs

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/MathHub#9]
I have started experimenting with setting up my private MathHub instance. 
Setup and configuration is really wonderfully easy and straightforward. But there are still problems. 
- [ ] we have no library; see #10 
- [ ] configure should allow to choose a port
- [ ] we need a good way the admin can configure which archives are served.

**Comment by tkw1536** [comment]
Current status:

When starting a private MathHub, this brings it's own everything. On startup, it takes a couple minutes to pull the detault set of archives. If you want a 'private MathHub' the current way of doing it is installing the individual components, like the frontend.

**Comment by kohlhase** [comment]
yes, I tested that and it was impressively easy. But I want more :-)
